name: buckshot
description: Template-driven UI framework for building modern web applications.
version: 0.0.1
dependencies:
  unittest:
    sdk: unittest
  dart-xml:
    git: git://github.com/prujohn/dart-xml.git
  DartNet-Event-Model:
    git: git://github.com/prujohn/DartNet-Event-Model.git
  Darternizr:
    git: git://github.com/prujohn/Darternizr.git